"""Decode Blueprint node graphs (K2Node exports + their UEdGraphPin lists) from an uncooked UE 5.7 package.

Pin serialization (worked out empirically against BP_MutableSoldier):
  pin ref   : int32 flag (0 = pin follows, 1 = null) · int32 owning node · FGuid
  pin body  : ref · owning node · FGuid · FName PinName · FText FriendlyName · int32 SourceIndex ·
              FString ToolTip · uint8 Direction · FEdGraphPinType · FString DefaultValue ·
              FString AutogeneratedDefault · int32 DefaultObject · FText DefaultText ·
              LinkedTo[] · SubPins[] · ParentPin ref · PassThrough ref · FGuid Persistent · int32 flags\n  node      : int32 bHasGuid · int32 NumPins · pins… · [class-specific extra data]
  pin type  : FName Category · FName SubCategory · int32 SubCategoryObject · uint8 ContainerType ·
              [Map only: FName TermCategory · FName TermSubCategory · int32 TermObject · 3×int32 bools] ·
              int32 bIsReference · int32 bIsConst · MemberRef{int32 parent · FName · FGuid} · 3×int32 bools
"""
import struct, collections
from uasset import Package, Reader

class Graph:
    def __init__(self, path):
        self.p = Package(path)
        self.d = self.p.d
        self.nodes = {}       # export index -> node dict
        self.graphs = {}      # graph export index -> name
        self.errors = []
        self._parse()

    # ---- primitives ----
    def fstring(self, r):
        n = r.i32()
        if n == 0: return ''
        if n < 0:
            s = self.d[r.o:r.o-2*n-2].decode('utf-16-le', 'replace'); r.o += -2*n; return s
        s = self.d[r.o:r.o+n-1].decode('utf-8', 'replace'); r.o += n; return s
    def ftext(self, r):
        r.u32(); hist = struct.unpack_from('<b', self.d, r.o)[0]; r.o += 1
        if hist == 0:
            self.fstring(r); self.fstring(r); return self.fstring(r)
        if hist == -1:
            return self.fstring(r) if r.i32() else ''
        if hist == 1:                                 # NamedFormat: source + {name: value}
            src = self.ftext(r)
            for _ in range(r.i32()): self.fstring(r); self.fmtarg(r)
            return src
        if hist == 2:                                 # OrderedFormat: source + [value]
            src = self.ftext(r)
            for _ in range(r.i32()): self.fmtarg(r)
            return src
        if hist == 3:                                 # ArgumentFormat: source + [(name, value)]
            src = self.ftext(r)
            for _ in range(r.i32()): self.fstring(r); self.fmtarg(r)
            return src
        raise ValueError('FText history %d' % hist)
    def fmtarg(self, r):
        t = struct.unpack_from('<b', self.d, r.o)[0]; r.o += 1
        if t == 0: r.o += 8          # Int    (int64)
        elif t == 1: r.o += 8        # UInt   (uint64)
        elif t == 2: r.o += 4        # Float
        elif t == 3: r.o += 8        # Double
        elif t == 4: self.ftext(r)   # Text
        elif t == 5: r.o += 1        # Gender
        else: raise ValueError('format arg type %d' % t)
    def fname(self, r):
        s = self.p.fname(r.o); r.o += 8; return s
    def guid(self, r):
        g = self.d[r.o:r.o+16].hex(); r.o += 16; return g
    def pinref(self, r):
        flag = r.i32()
        if flag == 1: return None
        if flag != 0: raise ValueError('pin ref flag %d' % flag)
        node = r.i32(); g = self.guid(r); return (node, g)

    def pintype(self, r):
        t = {}
        t['cat'] = self.fname(r); t['sub'] = self.fname(r); t['obj'] = r.i32()
        t['container'] = r.u8()
        if t['container'] == 3:                       # map: value type follows
            t['vcat'] = self.fname(r); t['vsub'] = self.fname(r); t['vobj'] = r.i32(); r.o += 12
        t['ref'] = r.i32(); t['const'] = r.i32()
        t['mparent'] = r.i32(); t['mname'] = self.fname(r); t['mguid'] = self.guid(r)
        r.o += 12
        return t

    def pin(self, r, owner):
        ref = self.pinref(r)
        if not ref or ref[0] != owner: raise ValueError('owning ref %r for node %d' % (ref, owner))
        node2 = r.i32(); g2 = self.guid(r)
        if (node2, g2) != ref: raise ValueError('pin header mismatch')
        pin = {'id': ref[1], 'name': self.fname(r), 'friendly': self.ftext(r)}
        r.i32()                                       # SourceIndex
        pin['tooltip'] = self.fstring(r)
        pin['dir'] = 'out' if r.u8() else 'in'
        pin['type'] = self.pintype(r)
        pin['default'] = self.fstring(r); pin['autodefault'] = self.fstring(r)
        pin['defobj'] = r.i32(); pin['deftext'] = self.ftext(r)
        pin['linked'] = [self.pinref(r) for _ in range(r.i32())]
        pin['subpins'] = [self.pinref(r) for _ in range(r.i32())]
        pin['parent'] = self.pinref(r); self.pinref(r)
        r.o += 16                                     # PersistentGuid
        pin['flags'] = r.u32()
        return pin

    # ---- package walk ----
    def _parse(self):
        p = self.p
        for i, e in enumerate(p.exports):
            cls = p.resolve(e['class']) or ''
            if cls == '/Script/Engine.EdGraph':
                self.graphs[i+1] = e['name']
        for i, e in enumerate(p.exports):
            cls = p.resolve(e['class']) or ''
            if 'K2Node' not in cls and 'EdGraphNode' not in cls: continue
            idx = i+1
            try:
                props = {pr['name']: pr['value'] for pr in p.export_props(e)}
                r = Reader(self.d, p.last_props_end)
                if r.i32(): r.o += 16
                npins = r.i32()
                pins = [self.pin(r, idx) for _ in range(npins)]
                end = e['offset'] + e['size']
                if r.o > end: raise ValueError('pins end at +%d, export at +%d' % (r.o-e['offset'], end-e['offset']))
                extra = end - r.o                     # class-specific data (user-defined pins etc.)
                self.nodes[idx] = {'idx': idx, 'name': e['name'], 'cls': cls.split('.')[-1],
                                   'graph': self.graphs.get(e['outer'], p.resolve(e['outer'])),
                                   'props': props, 'pins': pins, 'extra': extra}
            except Exception as ex:
                self.errors.append((idx, e['name'], cls.split('.')[-1], repr(ex)))

if __name__ == '__main__':
    import sys
    g = Graph(sys.argv[1])
    print('nodes parsed:', len(g.nodes), '| failed:', len(g.errors))
    by = collections.Counter(c for _,_,c,_ in g.errors)
    for c, n in by.most_common(): print('   fail', n, c)
    for err in g.errors[:6]: print('   ', err)
